// apps/web/src/shared/api/endpoints/index.ts

export * from './auth'
export * from './users'
export * from './exams'
export * from './questions'
export * from './tasks'
export * from './notifications'
export * from './results'
export * from './dashboard'
export * from './favorites'
export * from './papers'
export * from './profile'
export * from './wrongQuestions'
export * from './settings'
