// apps/web/src/shared/api/endpoints/index.ts

export * from './auth'
export * from './dashboard'
export * from './discussions'
export * from './exams'
export * from './favorites'
export * from './leaderboard'
export * from './learningProgress'
export * from './logs'
export * from './menu'
export * from './notifications'
export * from './orgs'
export * from './papers'
export * from './profile'
export * from './questions'
export * from './results'
export * from './roles'
export * from './settings'
export * from './smartPaper'
export * from './tasks'
export * from './users'
export * from './wrongQuestions'
