export * from './auth'
export * from './dashboard'
export * from './discussions'
export * from './favorites'
export * from './leaderboard'
export * from './learningProgress'
export * from './logs'
export * from './menu'
export * from './notifications'
export * from './orgs'
export * from './papers'
export * from './profile'
export * from './results'
export * from './roles'
export * from './smartPaper'
export * from './tasks'
export * from './users'
export * from './wrongQuestions'
export * from './files'
export * from './dicts'
export * from './systemConfigs'
export * from './jobs'
export * from './cache'
export * from './integrations'
export * from './announcements'
export * from './notificationUploads'
export * from './ai'
export * from './ai-logs'
export * from './system-tests'
export * from './proctoring'
export * from './workflows'
export { adminSettingsApi } from './admin-settings'

// ✅ 统一导出设置相关：系统设置(settingsApi) + 个人设置(userSettingsApi)
export { settingsApi, userSettingsApi } from './settings'

// —— exams 与 questions 显式导出（避免类型冲突）——
export { exams as examsApi } from './exams'
export type { Question as ExamQuestion, QuestionType as ExamQuestionType } from './exams'

export { questions as questionsApi } from './questions'
export type { Question, QuestionType, Difficulty } from './questions'
