_format_version: "3.0"

services:
  - name: auth-v1
    url: http://auth:9999
    routes:
      - name: auth-v1-route
        strip_path: true
        paths:
          - /auth/v1
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:5173
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - Authorization
          exposed_headers:
            - Content-Length
            - Content-Type
          credentials: true
          max_age: 3600
          preflight_continue: false