CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  jti VARCHAR(64) NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  user_agent VARCHAR(255),
  ip VARCHAR(64),
  revoked TINYINT(1) DEFAULT 0,
  replaced_by_jti VARCHAR(64) DEFAULT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user (user_id),
  UNIQUE KEY uniq_jti (jti),
  INDEX idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
